language: python
python:
  - "2.7"
before_install:
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b -p /home/travis/miniconda
  - export PATH=/home/travis/miniconda/bin:$PATH
  - conda update --yes conda
install:
  - conda create --yes -q -n pyenv python=2.7 numpy=1.9.2 scipy=0.16.0 nose=1.3.7
  - source activate pyenv
  - pip install MDAnalysis==0.12
  - pip install coveralls tempdir
  - chmod +x ./
script:
  - ./nosetests --with-coverage --cover-package diffusion_analysis test_diffusion_analysis.py
after_success:
  - coveralls
